"""add entertainment table

Revision ID: 057ed00f2013
Revises: 7ea6aae3ff3c
Create Date: 2024-05-14 17:28:49.211457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057ed00f2013'
down_revision = '7ea6aae3ff3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entertainment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ent_type', sa.String(), nullable=True),
    sa.Column('hourly_fee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('vendor_type', sa.String(), nullable=True),
    sa.Column('per_person_fee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vendor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('vendor_type', sa.VARCHAR(), nullable=True),
    sa.Column('per_person_fee', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vendors')
    op.drop_table('entertainment')
    # ### end Alembic commands ###
