"""empty message

Revision ID: c94eee78ec32
Revises: 1ca7a4434813
Create Date: 2024-05-16 14:08:37.725501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94eee78ec32'
down_revision = '1ca7a4434813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
