"""empty message

Revision ID: c94ed8479a8b
Revises: 462f3361df67
Create Date: 2024-05-15 15:54:34.423456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94ed8479a8b'
down_revision = '462f3361df67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.INTEGER(), nullable=True))
        batch_op.alter_column('end_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
